### PR TITLE
Support for CORS

### PR DESCRIPTION
**Pull request by veggiemonk**
Small modification to support CORS by adding the header `Access-Control-Allow-Origin: *`

I really wanted that feature in budo :smile:

### CODE REVIEW

**Comment by mattdesl** [comment]
Thanks! Do you think this should be the default?

**Comment by mattdesl** [comment]
Seems like [http-server](https://github.com/indexzero/http-server/blob/0c02f823f5e4311ad4247629f5b6131ffd09a958/README.md#available-options) uses an option, so I guess we can too. :smile:

**Comment by mattdesl** [comment]
Merged, thanks again. :tada:

**Comment by veggiemonk** [comment]
Cool. Let me know if there are other things on the roadmap :smile:

**Pull request merged**
