### PR TITLE
Insert base tag in generated HTML page for pushstate

### PR DESCRIPTION
**Pull request by mantoni**
This improves / fixes the pushstate generated HTML page as discussed in #159 and builds on top of a new feature introduced in https://github.com/mattdesl/simple-html-index/pull/11.

There are two commits:

- The first fixes the tests according to the changes that where made in `simple-html-index` unrelated to the base URL feature.
- The second commit contains the actual changes relevant for the pushstate base URL issue.

### CODE REVIEW

**Comment by mantoni** [comment]
I just noticed that #137 does the same thing and can be closed when this lands.

**Comment by mattdesl** [comment]
Thanks! This should probably be set through an option to avoid surprises to the end user. Like --base option which defaults to '/', or could be passed like --base=foo/

Cheers

**Comment by mantoni** [comment]
Yes, I thought about that also. However, when generating a default bundle and using `pushstate` it's currently broken as described in #159. This is why I watned to always enable it in case `pushstate` is enabled.

Making this a config could be done as a separate feature - however I don't see how this makes sense because a local server with the generated HTML page can not be served under a different base URL.

**Comment by mattdesl** [comment]
I don't think budo is "broken" — it just is a side effect of developing a site with push state (which no longer acts as a simple static server). Other frameworks like Angular also suggest manually adding a base tag:
https://angular.io/docs/ts/latest/guide/router.html#!#base-href

It seems better than having budo add it automagically, since it will lead to more developer confusion. Example: user is developing with an auto-generated index.html, and when they write their own HTML index file everything breaks since budo was doing something magic unbeknownst to them.

Another thing is that `/` for all relative URLs it not a "default" — so it will be weird if budo all of a sudden changes its relative URL format based on the `--pushstate` flag.

For now I think the best approach is just to enforce something like:

```sh
budo index.js --pushstate --base='/'
```

Now that I'm back from vacation I will have more bandwidth to merge & fix these PRs. Thanks! :smile:

**Comment by mantoni** [comment]
Ok. Fair points. Now that I am on holidays, the necessary change will have to wait until next week :)

**Comment by mantoni** [comment]
Ok, I changed the last commit to add the `base` option as discussed. If it is provided without a value it will default to `/`, otherwise the value is used as the base path. Also added a test file for the new option covering those two use cases

Let me know if this can be further improved.

**Comment by mantoni** [comment]
Now also added documentation to the nice markdown files in the `/docs` directory as a separate commit. Do you want me to squash those?

**Comment by mattdesl** [comment]
Awesome, thanks so much! 🎉 🍻 😄

**Comment by mattdesl** [comment]
pushed to 8.4.0

**Pull request merged**
