### PR TITLE
Added support for middleware in CLI

### PR DESCRIPTION
**Pull request by tornqvist**
Makes this possible:

```
$ budo src/index.js:app.js -dir public -middleware src/middleware/postcss
```

Having to use the API just to add custom middleware was getting tedious. In this way you only need to write the middleware or install commonly used middleware from npm. ✌️

### CODE REVIEW

**Comment by mattdesl** [comment]
This is really cool, thanks for the PR! :tada:

I've branched off your work and made a few tweaks:
https://github.com/mattdesl/budo/tree/feature/cli-middleware

Things to ponder on:

- I'm using `resolve` since it's a standard browserify/node way of looking up module names
- Many middleware modules (see [here](https://github.com/senchalabs/connect#middleware)) are actually a function that *returns* a middleware. I wonder if we should do a similar pattern; for example, the function takes `options` (from budo, things like budo's working directory) and the user is expected to return a middleware function.
- Most middlewares will need some sort of options, I'm not sure how useful it is just to expect them to be already configured. Maybe we could take a page from Browserify's book and pass arguments in with the array syntax... hmm..

**Comment by tornqvist** [comment]
That all makes sense. We could use [subarg](https://github.com/substack/subarg) instead of minimist and have nested arguments that way but the syntax would be kind of verbose, but maybe that's not an issue? My best attempt would look something like:
```
$ budo index.js --middleware [ my-middleware --key value ]
```

**Comment by mattdesl** [comment]
I've pushed some changes in my branch to support subarg and allow options to the middleware flags. Still not 100% sure about this feature since it adds a lot of complexity and API surface without much gain. I feel like only a minority of middlewares can be included without config — even simple ones like `serve-index` need an argument passed to them. At a certain point it's easier to just do something like this:

```js
// dev.js

var serveIndex = require('serve-index')
var compress = require('compression')

require('budo').cli(process.argv.slice(2), {
  middleware: [
    compress(),
    serveIndex(__dirname)
  ]
})
```

And then treat that like your custom budo:

```sh
node dev.js src/index.js:bundle.js --live --dir app -- -t babelify
```

**Comment by mattdesl** [comment]
As with my last message, I still feel this adds too much bloat/complexity for what it's worth. I'm going to close the PR, but the code above should work as an alternative.

Sorry! And thanks for your interest in the first place. :smile:

**Comment by tornqvist** [comment]
Sorry for the absence. It makes sense and I actually resolved to use something similar to your example. Thanks for taking your time.

**Pull request closed without merging**
