### PR TITLE
enable livereload on directories, not strictly files ending with `.html` (fixes #72)

### LINKED ISSUE #72: Pages must end in `.html` for LiveReload script to be injected
1. create a directory called `demo` and place in it an `index.html` with a `<script src="../bundle.js">`.
2. run budo.
3. load [http://localhost:9966/demo/](http://localhost:9966/demo/) in your browser.
4. view source.
5. notice the LiveReload script wasn't injected into the HTML response.

because the router whitelists only `*.html`, the script doesn't get injected. same thing happens for files ending in `.htm` (not `.html`).

the correct but slow thing would be to check the mime-type after ecstatic reads the file. but we don't want to muck with the stream, and since it's already a dev tool intended for serving `.html` files, we ought to just tweak the route's regex.

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by cvan** [comment]
[here's a prior patch](https://gist.github.com/cvan/bedf9311b654b280f03a), but I like this better

**Comment by mattdesl** [comment]
I added `example/demo/index.html` and tried testing like so:

```sh
./bin/cmd.js test/fixtures/app:bundle.js --dir example/ --live | garnish
```

But the `index.html` request never finishes. This is something to do with `inject-lr-script`.

Could also explore [inject-lr-script-stream](https://github.com/yoshuawuyts/inject-lr-script-stream) and avoid the mime-type check, but might involve changing `ecstatic` to something simpler like `filed`.

**Comment by cvan** [comment]
> But the `index.html` request never finishes. This is something to do with `inject-lr-script`.

Yep, I noticed that on budo master too. I was going to troubleshoot that but forgot. Separate issue?

**Comment by mattdesl** [comment]
Ah must be a separate issue then :smile:

**Comment by cvan** [comment]
> Yep, I noticed that on budo master too. I was going to troubleshoot that but forgot. Separate issue?

Actually, looks like I regressed it here heh. Investigating…

**Comment by cvan** [comment]
But a similar issue exists on `master`:

http://localhost:9966/404.html will keep loading.

**Comment by cvan** [comment]
would you be willing to merge this? I still am encountering #79 but it looks to be a separate issue. and I spent some time trying to tackle #80, but it took quite some time - would like to revisit it sometime though.

**Comment by mattdesl** [comment]
I just tested again and it doesn't seem to hang. Merged! Thanks

**Comment by mattdesl** [comment]
I'm doing more tests locally and this seems to break some functionality. It looks like images and other files are getting picked up by the regex. I will keep investigating.

**Comment by mattdesl** [comment]
I added a new regex when not in `--pushstate` mode, let me know if it's working in v7.

**Pull request merged**
